services:
  # Main bridge application
  bridge-app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_ETHEREUM_RPC_URL=${ETHEREUM_RPC_URL:-https://sepolia.infura.io/v3/your-key}
      - NEXT_PUBLIC_NEAR_RPC_URL=${NEAR_RPC_URL:-https://rpc.testnet.near.org}
      - NEXT_PUBLIC_ETHEREUM_CHAIN_ID=11155111
      - NEXT_PUBLIC_NEAR_NETWORK_ID=testnet
      - NEXT_PUBLIC_ENABLE_REAL_TRANSACTIONS=true
    restart: unless-stopped